// tauri-app/src/components/CommandInput.tsx
import { useState } from "react";
import "./CommandInput.css";

interface CommandInputProps {
  onSubmit: (input: string) => void;
  disabled?: boolean;
}

export function CommandInput({ onSubmit, disabled }: CommandInputProps) {
  const [input, setInput] = useState("");

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (input.trim() && !disabled) {
      onSubmit(input.trim());
      setInput("");
    }
  };

  return (
    <div className="command-input-container">
      <h2>💬 Command Input</h2>
      <form onSubmit={handleSubmit} className="command-form">
        <textarea
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Describe what you want to create in Godot...&#10;&#10;Example: Add a 2D player character with a sprite and collision shape"
          disabled={disabled}
          rows={4}
          className="command-textarea"
        />
        <button type="submit" disabled={disabled || !input.trim()} className="submit-button">
          {disabled ? "⏸ Not Ready" : "🚀 Execute"}
        </button>
      </form>
      {disabled && (
        <p className="warning-text">
          ⚠️ Please configure your API key and ensure Godot is connected
        </p>
      )}
    </div>
  );
}

// tauri-app/src/app/components/command-input/command-input.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-command-input',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './command-input.component.html',
  styleUrls: ['./command-input.component.css']
})
export class CommandInputComponent {
  @Input() disabled: boolean = false;
  @Output() submitCommand = new EventEmitter<string>();

  input: string = '';

  handleSubmit(event: Event): void {
    event.preventDefault();
    if (this.input.trim() && !this.disabled) {
      this.submitCommand.emit(this.input.trim());
      this.input = '';
    }
  }
}


<div class="command-input-container">
  <h2>💬 Command Input</h2>
  <form (ngSubmit)="handleSubmit($event)" class="command-form">
    <textarea
      [(ngModel)]="input"
      name="commandInput"
      placeholder="Describe what you want to create in Godot...&#10;&#10;Example: Add a 2D player character with a sprite and collision shape"
      [disabled]="disabled"
      rows="4"
      class="command-textarea"
    ></textarea>
    <button type="submit" [disabled]="disabled || !input.trim()" class="submit-button">
      {{ disabled ? '⏸ Not Ready' : '🚀 Execute' }}
    </button>
  </form>
  <p *ngIf="disabled" class="warning-text">
    ⚠️ Please configure your API key and ensure Godot is connected
  </p>
</div>
