// tauri-app/src/app/components/command-history/command-history.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Command } from '../../models/command.model';

@Component({
  selector: 'app-command-history',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './command-history.component.html',
  styleUrls: ['./command-history.component.css']
})
export class CommandHistoryComponent {
  @Input() commands: Command[] = [];

  formatTime(date: Date): string {
    return date.toLocaleTimeString();
  }

  getStatusIcon(status: Command['status']): string {
    switch (status) {
      case 'success':
        return '✅';
      case 'error':
        return '❌';
      case 'pending':
        return '⏳';
    }
  }
}


<div class="command-history-container">
  <h2>📜 Command History</h2>
  <div class="history-list">
    <p *ngIf="commands.length === 0" class="empty-message">
      No commands yet. Start by typing a command above!
    </p>
    <div
      *ngFor="let command of commands"
      [class]="'history-item status-' + command.status"
    >
      <div class="history-header">
        <span class="status-icon">{{ getStatusIcon(command.status) }}</span>
        <span class="timestamp">{{ formatTime(command.timestamp) }}</span>
      </div>
      <div class="command-input">{{ command.input }}</div>
      <div *ngIf="command.response" class="command-response">
        <strong>Response:</strong> {{ command.response }}
      </div>
    </div>
  </div>
</div>

// tauri-app/src/components/CommandHistory.tsx
import "./CommandHistory.css";

interface Command {
  id: string;
  input: string;
  timestamp: Date;
  status: "pending" | "success" | "error";
  response?: string;
}

interface CommandHistoryProps {
  commands: Command[];
}

export function CommandHistory({ commands }: CommandHistoryProps) {
  const formatTime = (date: Date) => {
    return date.toLocaleTimeString();
  };

  const getStatusIcon = (status: Command["status"]) => {
    switch (status) {
      case "success":
        return "✅";
      case "error":
        return "❌";
      case "pending":
        return "⏳";
    }
  };

  return (
    <div className="command-history-container">
      <h2>📜 Command History</h2>
      <div className="history-list">
        {commands.length === 0 ? (
          <p className="empty-message">No commands yet. Start by typing a command above!</p>
        ) : (
          commands.map((command) => (
            <div key={command.id} className={`history-item status-${command.status}`}>
              <div className="history-header">
                <span className="status-icon">{getStatusIcon(command.status)}</span>
                <span className="timestamp">{formatTime(command.timestamp)}</span>
              </div>
              <div className="command-input">{command.input}</div>
              {command.response && (
                <div className="command-response">
                  <strong>Response:</strong> {command.response}
                </div>
              )}
            </div>
          ))
        )}
      </div>
    </div>
  );
}
