// tauri-app/src/app/components/settings-panel/settings-panel.component.ts
import { Component, EventEmitter, Input, Output, OnChanges, SimpleChanges } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-settings-panel',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './settings-panel.component.html',
  styleUrls: ['./settings-panel.component.css']
})
export class SettingsPanelComponent implements OnChanges {
  @Input() apiKey: string = '';
  @Output() saveApiKey = new EventEmitter<string>();
  @Output() reconnect = new EventEmitter<void>();

  editingKey: boolean = false;
  tempKey: string = '';

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['apiKey']) {
      this.tempKey = this.apiKey;
    }
  }

  handleSave(): void {
    this.saveApiKey.emit(this.tempKey);
    this.editingKey = false;
  }

  handleCancel(): void {
    this.tempKey = this.apiKey;
    this.editingKey = false;
  }

  handleReconnect(): void {
    this.reconnect.emit();
  }
}


<div class="settings-panel-container">
  <h2>⚙️ Settings</h2>

  <div class="settings-section">
    <h3>OpenRouter API Key</h3>
    <div *ngIf="editingKey" class="api-key-edit">
      <input
        type="password"
        [(ngModel)]="tempKey"
        placeholder="sk-or-..."
        class="api-key-input"
      />
      <div class="button-group">
        <button (click)="handleSave()" class="save-button">
          💾 Save
        </button>
        <button (click)="handleCancel()" class="cancel-button">
          ❌ Cancel
        </button>
      </div>
    </div>
    <div *ngIf="!editingKey" class="api-key-display">
      <div class="api-key-status">
        {{ apiKey ? '✅ Configured' : '❌ Not configured' }}
      </div>
      <button (click)="editingKey = true" class="edit-button">
        ✏️ Edit
      </button>
    </div>
  </div>

  <div class="settings-section">
    <h3>Connection</h3>
    <button (click)="handleReconnect()" class="reconnect-button">
      🔄 Reconnect to Godot
    </button>
    <p class="info-text">
      Make sure the Godoty plugin is enabled in your Godot project and the editor is running.
    </p>
  </div>

  <div class="settings-section">
    <h3>About</h3>
    <p class="info-text">
      Godoty AI Assistant helps you build games in Godot using natural language commands.
    </p>
    <p class="info-text">
      Version: 0.1.0
    </p>
  </div>
</div>

// tauri-app/src/components/SettingsPanel.tsx
import { useState } from "react";
import "./SettingsPanel.css";

interface SettingsPanelProps {
  apiKey: string;
  onSaveApiKey: (key: string) => void;
  onReconnect: () => void;
}

export function SettingsPanel({ apiKey, onSaveApiKey, onReconnect }: SettingsPanelProps) {
  const [editingKey, setEditingKey] = useState(false);
  const [tempKey, setTempKey] = useState(apiKey);

  const handleSave = () => {
    onSaveApiKey(tempKey);
    setEditingKey(false);
  };

  const handleCancel = () => {
    setTempKey(apiKey);
    setEditingKey(false);
  };

  return (
    <div className="settings-panel-container">
      <h2>⚙️ Settings</h2>

      <div className="settings-section">
        <h3>OpenAI API Key</h3>
        {editingKey ? (
          <div className="api-key-edit">
            <input
              type="password"
              value={tempKey}
              onChange={(e) => setTempKey(e.target.value)}
              placeholder="sk-..."
              className="api-key-input"
            />
            <div className="button-group">
              <button onClick={handleSave} className="save-button">
                💾 Save
              </button>
              <button onClick={handleCancel} className="cancel-button">
                ❌ Cancel
              </button>
            </div>
          </div>
        ) : (
          <div className="api-key-display">
            <div className="api-key-status">
              {apiKey ? "✅ Configured" : "❌ Not configured"}
            </div>
            <button onClick={() => setEditingKey(true)} className="edit-button">
              ✏️ Edit
            </button>
          </div>
        )}
      </div>

      <div className="settings-section">
        <h3>Connection</h3>
        <button onClick={onReconnect} className="reconnect-button">
          🔄 Reconnect to Godot
        </button>
        <p className="info-text">
          Make sure the Godoty plugin is enabled in your Godot project and the editor is running.
        </p>
      </div>

      <div className="settings-section">
        <h3>About</h3>
        <p className="info-text">
          Godoty AI Assistant helps you build games in Godot using natural language commands.
        </p>
        <p className="info-text">
          Version: 0.1.0
        </p>
      </div>
    </div>
  );
}
