// tauri-app/src/app/components/status-panel/status-panel.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ConnectionStatus } from '../../models/command.model';

@Component({
  selector: 'app-status-panel',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './status-panel.component.html',
  styleUrls: ['./status-panel.component.css']
})
export class StatusPanelComponent {
  @Input() status: ConnectionStatus = 'disconnected';

  getStatusIcon(): string {
    switch (this.status) {
      case 'connected':
        return '🟢';
      case 'connecting':
        return '🟡';
      case 'disconnected':
        return '🔴';
    }
  }

  getStatusText(): string {
    switch (this.status) {
      case 'connected':
        return 'Connected to Godot';
      case 'connecting':
        return 'Connecting...';
      case 'disconnected':
        return 'Disconnected';
    }
  }
}


<div [class]="'status-panel status-' + status">
  <span class="status-icon">{{ getStatusIcon() }}</span>
  <span class="status-text">{{ getStatusText() }}</span>
</div>

// tauri-app/src/components/StatusPanel.tsx
import "./StatusPanel.css";

interface StatusPanelProps {
  status: "disconnected" | "connecting" | "connected";
}

export function StatusPanel({ status }: StatusPanelProps) {
  const getStatusIcon = () => {
    switch (status) {
      case "connected":
        return "🟢";
      case "connecting":
        return "🟡";
      case "disconnected":
        return "🔴";
    }
  };

  const getStatusText = () => {
    switch (status) {
      case "connected":
        return "Connected to Godot";
      case "connecting":
        return "Connecting...";
      case "disconnected":
        return "Disconnected";
    }
  };

  return (
    <div className={`status-panel status-${status}`}>
      <span className="status-icon">{getStatusIcon()}</span>
      <span className="status-text">{getStatusText()}</span>
    </div>
  );
}
