// tauri-app/src/App.tsx
import { useState, useEffect } from "react";
import "./App.css";
import { CommandInput } from "./components/CommandInput";
import { StatusPanel } from "./components/StatusPanel";
import { CommandHistory } from "./components/CommandHistory";
import { SettingsPanel } from "./components/SettingsPanel";
import { invoke } from "@tauri-apps/api/core";

interface Command {
  id: string;
  input: string;
  timestamp: Date;
  status: "pending" | "success" | "error";
  response?: string;
}

function App() {
  const [commands, setCommands] = useState<Command[]>([]);
  const [connectionStatus, setConnectionStatus] = useState<"disconnected" | "connecting" | "connected">("disconnected");
  const [apiKey, setApiKey] = useState<string>("");

  useEffect(() => {
    // Load API key from storage
    loadApiKey();

    // Connect to Godot
    connectToGodot();
  }, []);

  const loadApiKey = async () => {
    try {
      const key = await invoke<string>("get_api_key");
      setApiKey(key);
    } catch (error) {
      console.error("Failed to load API key:", error);
    }
  };

  const connectToGodot = async () => {
    setConnectionStatus("connecting");
    try {
      await invoke("connect_to_godot");
      setConnectionStatus("connected");
    } catch (error) {
      console.error("Failed to connect to Godot:", error);
      setConnectionStatus("disconnected");
    }
  };

  const handleCommandSubmit = async (input: string) => {
    const command: Command = {
      id: Date.now().toString(),
      input,
      timestamp: new Date(),
      status: "pending",
    };

    setCommands((prev) => [command, ...prev]);

    try {
      // Process command with AI
      const response = await invoke<string>("process_command", { input });

      setCommands((prev) =>
        prev.map((cmd) =>
          cmd.id === command.id
            ? { ...cmd, status: "success", response }
            : cmd
        )
      );
    } catch (error) {
      setCommands((prev) =>
        prev.map((cmd) =>
          cmd.id === command.id
            ? { ...cmd, status: "error", response: String(error) }
            : cmd
        )
      );
    }
  };

  const handleSaveApiKey = async (key: string) => {
    try {
      await invoke("save_api_key", { key });
      setApiKey(key);
    } catch (error) {
      console.error("Failed to save API key:", error);
    }
  };

  return (
    <div className="app-container">
      <header className="app-header">
        <h1>🎮 Godoty AI Assistant</h1>
        <StatusPanel status={connectionStatus} />
      </header>

      <main className="app-main">
        <div className="left-panel">
          <CommandInput onSubmit={handleCommandSubmit} disabled={connectionStatus !== "connected" || !apiKey} />
          <CommandHistory commands={commands} />
        </div>

        <div className="right-panel">
          <SettingsPanel apiKey={apiKey} onSaveApiKey={handleSaveApiKey} onReconnect={connectToGodot} />
        </div>
      </main>
    </div>
  );
}

export default App;

// tauri-app/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { invoke } from '@tauri-apps/api/core';
import { Command, ConnectionStatus, ChatSession, MessageStatus } from './models/command.model';
import { CommandInputComponent } from './components/command-input/command-input.component';
import { StatusPanelComponent } from './components/status-panel/status-panel.component';
import { SettingsPanelComponent } from './components/settings-panel/settings-panel.component';
import { ChatViewComponent } from './components/chat-view/chat-view.component';
import { SessionManagerComponent } from './components/session-manager/session-manager.component';
import { ChatSelectorComponent } from './components/chat-selector/chat-selector.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    CommandInputComponent,
    StatusPanelComponent,
    SettingsPanelComponent,
    ChatViewComponent,
    SessionManagerComponent,
    ChatSelectorComponent
  ],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  commands: Command[] = [];
  connectionStatus: ConnectionStatus = 'disconnected';
  apiKey: string = '';
  projectPath: string = '';

  // Chat session management
  chatSessions: ChatSession[] = [];
  activeSession: ChatSession | null = null;

  // Processing state
  isProcessing: boolean = false;
  processingStatus: MessageStatus | null = null;

  ngOnInit(): void {
    this.loadApiKey();
    this.loadProjectPath();
    this.connectToGodot();
    this.loadChatSessions();
  }

  async loadApiKey(): Promise<void> {
    try {
      this.apiKey = await invoke<string>('get_api_key');
    } catch (error) {
      console.error('Failed to load API key:', error);
    }
  }

  async loadProjectPath(): Promise<void> {
    try {
      this.projectPath = await invoke<string>('get_godot_project_path');
    } catch (error) {
      console.error('Failed to load project path:', error);
    }
  }

  async connectToGodot(): Promise<void> {
    this.connectionStatus = 'connecting';
    try {
      await invoke('connect_to_godot');
      this.connectionStatus = 'connected';
    } catch (error) {
      console.error('Failed to connect to Godot:', error);
      this.connectionStatus = 'disconnected';
    }
  }

  async handleCommandSubmit(input: string): Promise<void> {
    const command: Command = {
      id: Date.now().toString(),
      input,
      timestamp: new Date(),
      status: 'pending'
    };

    this.commands = [command, ...this.commands];

    // Set processing state
    this.isProcessing = true;
    this.processingStatus = 'sending';

    try {
      // Update status to thinking
      this.processingStatus = 'thinking';

      const response = await invoke<string>('process_command', { input });

      // Update status to complete
      this.processingStatus = 'complete';

      this.commands = this.commands.map(cmd =>
        cmd.id === command.id
          ? { ...cmd, status: 'success', response }
          : cmd
      );

      // Reload active session to show new messages
      await this.loadActiveSession();
    } catch (error) {
      this.processingStatus = 'error';

      this.commands = this.commands.map(cmd =>
        cmd.id === command.id
          ? { ...cmd, status: 'error', response: String(error) }
          : cmd
      );

      // Reload active session even on error to show the error message
      await this.loadActiveSession();
    } finally {
      // Clear processing state after a short delay
      setTimeout(() => {
        this.isProcessing = false;
        this.processingStatus = null;
      }, 500);
    }
  }

  async handleSaveApiKey(key: string): Promise<void> {
    try {
      await invoke('save_api_key', { key });
      this.apiKey = key;
    } catch (error) {
      console.error('Failed to save API key:', error);
    }
  }

  async handleSaveProjectPath(path: string): Promise<void> {
    try {
      await invoke('set_godot_project_path', { path });
      this.projectPath = path;
    } catch (error) {
      console.error('Failed to save project path:', error);
    }
  }

  // Chat session management methods
  async loadChatSessions(): Promise<void> {
    try {
      const sessions = await invoke<ChatSession[]>('get_all_sessions');
      this.chatSessions = sessions;
      await this.loadActiveSession();
    } catch (error) {
      console.error('Failed to load chat sessions:', error);
      this.chatSessions = [];
    }
  }

  async loadActiveSession(): Promise<void> {
    try {
      this.activeSession = await invoke<ChatSession>('get_active_session');
    } catch (error) {
      // No active session is fine
      this.activeSession = null;
    }
  }

  async handleCreateSession(title: string): Promise<void> {
    try {
      await invoke('create_chat_session', { title });
      await this.loadChatSessions();
    } catch (error) {
      console.error('Failed to create session:', error);
    }
  }

  async handleSelectSession(sessionId: string): Promise<void> {
    try {
      await invoke('set_active_session', { sessionId });
      await this.loadActiveSession();
    } catch (error) {
      console.error('Failed to select session:', error);
    }
  }

  async handleDeleteSession(sessionId: string): Promise<void> {
    try {
      await invoke('delete_session', { sessionId });
      await this.loadChatSessions();
    } catch (error) {
      console.error('Failed to delete session:', error);
    }
  }

  async handleClearAllSessions(): Promise<void> {
    try {
      await invoke('clear_all_sessions');
      await this.loadChatSessions();
    } catch (error) {
      console.error('Failed to clear sessions:', error);
    }
  }

  async handleQuickCreateSession(): Promise<void> {
    const timestamp = new Date().toLocaleString();
    await this.handleCreateSession(`Chat ${timestamp}`);
  }
}


<div class="app-container">
  <header class="app-header">
    <div class="header-left">
      <h1>🎮 Godoty AI Assistant</h1>
    </div>
    <div class="header-controls">
      <app-status-panel [status]="connectionStatus"></app-status-panel>
    </div>
  </header>

  <main class="app-main">
    <div class="left-panel">
      <!-- Chat Selector Dropdown -->
      <app-chat-selector
        [sessions]="chatSessions"
        [activeSession]="activeSession"
        (selectSession)="handleSelectSession($event)"
        (createSession)="handleQuickCreateSession()"
      ></app-chat-selector>

      <!-- Chat View with Integrated Input -->
      <app-chat-view
        [session]="activeSession"
        [isProcessing]="isProcessing"
        [processingStatus]="processingStatus"
        [disabled]="connectionStatus !== 'connected' || !apiKey || !projectPath || isProcessing"
        (submitCommand)="handleCommandSubmit($event)"
      ></app-chat-view>
    </div>

    <div class="right-panel">
      <app-session-manager
        [sessions]="chatSessions"
        [activeSessionId]="activeSession?.id || null"
        (createSession)="handleCreateSession($event)"
        (selectSession)="handleSelectSession($event)"
        (deleteSession)="handleDeleteSession($event)"
        (clearAllSessions)="handleClearAllSessions()"
      ></app-session-manager>

      <app-settings-panel
        [apiKey]="apiKey"
        [projectPath]="projectPath"
        (saveApiKey)="handleSaveApiKey($event)"
        (saveProjectPath)="handleSaveProjectPath($event)"
        (reconnect)="connectToGodot()"
      ></app-settings-panel>
    </div>
  </main>
</div>
